### ISSUE TITLE
display 3D model

### ISSUE THREAD

**Issue by redDwarf03** [wasabia/three_dart#1]
Hello
I'm happy to find your project. it seems you actually work on it. What is the maturity of the project because I try to find some documentation.
I would like to display in my flutter app a 3D object from mtl and obj files host on an external server
https://dragginator.com/test/obj/test.obj
https://dragginator.com/test/obj/test2.mtl
Could you help me ? 
Thx

NB: I try to get in local the project but I have dependencies errors like three_dart_jsm missing

**Comment by wasabia** [comment]
Hi
check the example project 


three_dart_jsm is three.js/example/jsm, I separate it to a plugin.
three_dart_jsm plugin 
use this repo [git@github.com:wasabia/three_dart_jsm.git](git@github.com:wasabia/three_dart_jsm.git)

add to pubspec.yaml
```
  three_dart_jsm:
    git: git@github.com:wasabia/three_dart_jsm.git
```

**Comment by wasabia** [comment]
i have publish three_dart_jsm to pub, and fix the example project, you can pull the code then try run

**Comment by redDwarf03** [comment]
thx
i will propose a PR because I have some issues when I get the project in local.

Other things: when I do ```cd example; flutter run;```, I meet these errors

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: assets/screenshots/webgl_shadow_demo1.jpg

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:224:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:675:14)
<asynchronous suspension>

Image provider: AssetImage(bundle: null, name: "assets/screenshots/webgl_shadow_demo1.jpg")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#a4f3f(), name:
  "assets/screenshots/webgl_shadow_demo1.jpg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Unable to load asset: assets/screenshots/webgl_materials_browser.jpg
```

**Comment by redDwarf03** [comment]
another things: I changed the object and texture and I lost the connection with the device with this error: 
```Fatal error: Unexpectedly found nil while unwrapping an Optional value: file flutter_gl/CustomRender.swift, line 146```

**Comment by wasabia** [comment]
this happen every time?

**Comment by redDwarf03** [comment]
for the moment yes. I copied webgl_loader_obj class in my project. I added dependencies. I added assets. but each time, I have the fatal error (I don't have this fatal error with your project)

**Comment by wasabia** [comment]
you can check flutter_gl project readme
you need init flutter_gl plugin to prepare opengl context

**Comment by wasabia** [comment]
[https://github.com/wasabia/flutter_gl#usage](https://github.com/wasabia/flutter_gl#usage)

**Comment by wasabia** [comment]
maybe i can wrapper it in a widget, so user no need to handle it by self....

**Comment by redDwarf03** [comment]
I am ashamed... I forget to add assets in pubspec.yaml... so it works better.... I should continue to test

For info, I try to launch with android. I think you could add in the documentation of this project
- add threeagl.aar file 
- change minSdkVersion eq 24

**Comment by redDwarf03** [comment]
> you can check flutter_gl project readme
> you need init flutter_gl plugin to prepare opengl context

if we copy in the user project webgl_loader_obj class from example folder, the initialization is ok :)

**Comment by wasabia** [comment]
now i have a problem, if you want to display 3D model
glb is best choice?  
but now i can not implement draco loader ...

**Comment by redDwarf03** [comment]
my goal is to display in mobile app this: https://dragginator.com/test/obj/

i want to move the object like in chrome. 
the asset is here:
https://dragginator.com/test/obj/test.obj
https://dragginator.com/test/obj/test2.mtl
https://dragginator.com/test/obj/texture_map.png

**Comment by wasabia** [comment]
ok it is possiable to display it with three_dart,
maybe the controls need to implement by self 
flutter has no dom listener

**Comment by redDwarf03** [comment]
great!
I meet pb to get there. maybe you can add this example in your examples? 
furthermore, is it possible to remove the word 'render' and the default debug banner please?

**Comment by wasabia** [comment]
now support obj  gltf 3d Model

**Comment by redDwarf03** [comment]
I should use GitHub dependencies instead of pub.Dev ?

**Comment by wasabia** [comment]
> great! I meet pb to get there. maybe you can add this example in your examples? furthermore, is it possible to remove the word 'render' and the default debug banner please?

remove word 'render' debug banner? 

you mean the screen bottom blue round button render? it is just flutter widget, off course you can remove it.
debug label on screen top? when you release you flutter app in release mode it is gone

**Comment by wasabia** [comment]
> I should use GitHub dependencies instead of pub.Dev ?

it is depend you, if pub version work ok, you can use pub version

**Comment by redDwarf03** [comment]
> now i have a problem
any idea?

**Comment by wasabia** [comment]
> > now i have a problem
> 
> any idea?

need a guys know c or c++ or use rust wrapper it  export draco api then call it by ffi
