### ISSUE TITLE
Member not found: 'PI'.

### ISSUE THREAD

**Issue by md-sazzadul-islam** [wasabia/three_dart#105]
Member not found: 'Infinity'.
  var Infinity = Math.Infinity;

Member not found: 'PI'.
  var twoPI = 2 * Math.PI;

![Screenshot_3](https://user-images.githubusercontent.com/26510351/201710258-5a1779f8-2094-482d-b463-8aa719099c00.png)

**Comment by wasabia** [comment]
Hi @md-sazzadul-islam 
try latest code
