### ISSUE TITLE
Use for transition effects

### ISSUE THREAD

**Issue by cdigit** [wasabia/three_dart#111]
Hi, I have a desire to make image slideshows or sliders like the ones below that make use of three.js. I'm new to this web_gl , open_gl world, but I was wondering if three_dart can help with making transitions like the ones seen below? Is it possible to do in Flutter or at least some approximation?

- [Image slider](https://codepen.io/kenjiSpecial/pen/EaVxdx)
- [Texture slider](https://splidejs.com/premium/)
- [3D Slider](https://codepen.io/UIUXLab/pen/rvZXQQ)
- [Three.js particle slider](https://codepen.io/cjp/pen/MGwPMb)

**Comment by wasabia** [comment]
Yes. it is very sure to implement these effects in Flutter with three_dart.

**Comment by cdigit** [comment]
Thanks for letting me know.
Can you briefly explain the difference between this three dart project and the current wasabia project: https://github.com/threeDart/three.dart

**Comment by wasabia** [comment]
i did't know [three.dart](https://github.com/threeDart/three.dart) 

three_dart: call native graphics api（OpenGL ES）through Dart FFI.

**Comment by cdigit** [comment]
Thanks
