### ISSUE TITLE
StereoCamera not working

### ISSUE THREAD

**Issue by JustFrederik** [wasabia/three_dart#126]
I tried to implement the StereoCamera. I just created a second renderer to render each eye. The problem is eyeSep and aspect, both dont have an effect. The Cameras are equal. Heres a gist with my code.
[https://gist.github.com/JustFrederik/911e37e8174129768730d84e2db9ab78](https://gist.github.com/JustFrederik/911e37e8174129768730d84e2db9ab78)

**Comment by wasabia** [comment]
[https://github.com/wasabia/three_dart/blob/main/lib/three3d/cameras/stereo_camera.dart](https://github.com/wasabia/three_dart/blob/main/lib/three3d/cameras/stereo_camera.dart)
not working?


[https://github.com/mrdoob/three.js/blob/dev/src/cameras/StereoCamera.js](https://github.com/mrdoob/three.js/blob/dev/src/cameras/StereoCamera.js)

StereoCamera is one renderer two camera, not two renderer

**Comment by JustFrederik** [comment]
I ported StereoEffect, which is now in jsm
