### ISSUE TITLE
Does this library support Render to a Texture?

### ISSUE THREAD

**Issue by andyzhshg** [wasabia/three_dart#129]
First of all, thank you for providing such a great library. I would like to ask a question.

I want to use an offline rendering buffer as a texture, but I haven't found how to do it. Are there any related examples that I can refer to? Thank you.

**Comment by wasabia** [comment]
offscreen render ?  
It's supported

**Comment by andyzhshg** [comment]
Thanks for reply. I'll try to find other ways.
