### ISSUE TITLE
Flutter gltf error

### ISSUE THREAD

**Issue by semihpolatt** [wasabia/three_dart#16]
It doesn't load gltf files. Even in the example on github it doesn't load

**Comment by wasabia** [comment]
[https://wasabia.github.io/three_dart_example/#/examples/webgl_loader_gltf](https://wasabia.github.io/three_dart_example/#/examples/webgl_loader_gltf)

this link do not work?

maybe need more time to load gltf


![gltf](https://user-images.githubusercontent.com/1768228/158829941-aef26308-421f-4bd8-b56c-2d2c99a2330d.jpg)

**Comment by semihpolatt** [comment]
Actually not animated gltf files are loading. But that pages are not on my browser. I even downloaded codes and gltf files, still doesn't work. By the way this is amazing library! Thank you very much! for my opinion you are developing most important library in the pub.dev  

And I have a last question? Can we import .fbx files and animate them? I searched in codes but I couldn't find

<img width="1436" alt="Screen Shot 2022-03-18 at 02 58 29" src="https://user-images.githubusercontent.com/72199891/158912588-1b75a13f-404b-4024-acd1-acf61f57a097.png">

<img width="888" alt="Screen Shot 2022-03-18 at 02 58 55" src="https://user-images.githubusercontent.com/72199891/158912619-a2634283-dcd6-4ca4-ad89-813f97304e2f.png">

<img width="453" alt="Screen Shot 2022-03-18 at 02 59 18" src="https://user-images.githubusercontent.com/72199891/158912643-2ce2adb8-521f-4a1f-a3da-8acd68946116.png">

<img width="436" alt="Screen Shot 2022-03-18 at 02 59 32" src="https://user-images.githubusercontent.com/72199891/158912659-dc3a3880-993a-4a5a-b035-347a02e6bfcb.png">

<img width="399" alt="Screen Shot 2022-03-18 at 03 00 03" src="https://user-images.githubusercontent.com/72199891/158912709-1d89cacc-e029-496f-8eb5-217bfcb6ca9d.png">

**Comment by wasabia** [comment]
any error in console ?

.fbx is not support now.

**Comment by wasabia** [comment]
gltf error on andorid?

**Comment by MapleNoise** [comment]
On my log, all seem to work fine :

> {scene: Instance of 'Group', scenes: [Instance of 'Group'], animations: [Instance of 'AnimationClip'], cameras: [], asset: {generator: Khronos glTF Blender I/O v1.5.17, version: 2.0}, parser: Instance of 'GLTFParser', userData: {}}
I/flutter (22633):  load gltf success result: {scene: Instance of 'Group', scenes: [Instance of 'Group'], animations: [Instance of 'AnimationClip'], cameras: [], asset: {generator: Khronos glTF Blender I/O v1.5.17, version: 2.0}, parser: Instance of 'GLTFParser', userData: {}}  
I/flutter (22633):  load gltf success model: Instance of 'Group'  
I/flutter (22633): render cost: 2559 
I/flutter (22633): {geometries: 83, textures: 15}
I/flutter (22633): {frame: 35.0, calls: 78, triangles: 142369.0, points: 0, lines: 0}
I/flutter (22633):  render: sourceTexture: 3 
I/System.out(22633): Results of compiling source:
I/System.out(22633): Results of compiling source:
I/flutter (22633): render cost: 32 
I/flutter (22633): {geometries: 83, textures: 15}
I/flutter (22633): {frame: 36.0, calls: 78, triangles: 142369.0, points: 0, lines: 0}
I/flutter (22633):  render: sourceTexture: 3 
I/flutter (22633): render cost: 31 
I/flutter (22633): {geometries: 83, textures: 15}
...
...

I check my android config: min sdk, gradle version, Manifest, import aars lib, etc... all is similar

**Comment by wasabia** [comment]
can you provide a example project can reproduce the problem

**Comment by MapleNoise** [comment]
Yes, I tested with webgl_loader_obj_mtl widget on my project and I've this black screen too. I tried to add like a widget and like a push MaterialPageRoute.

I will try with flutter_gl, and create a small project sample with the problem if I can.

I add your library on my big project (Flutter Pokemon GO like) so it can be difficult to provide the sample of this project part 🥲

**Comment by MapleNoise** [comment]
I finally find the problem...

I don't understand why... But when I add this line on my main() function :
`FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);` your library provide a black screen 

Just remove and it works
