### ISSUE TITLE
DecalGeometry Missing

### ISSUE THREAD

**Issue by vraj129** [wasabia/three_dart#163]
This library is missing the functionality of DecalGeomety, or has any one done in there local project using this library can this be shared.

**Comment by Knightro63** [comment]
Hi @vraj129,

You can get it from [here](https://github.com/Knightro63/three_js/blob/main/packages%2Fthree_js_geometry%2Flib%2Fdecal_geometry.dart). You might need to make some changes to get it to work in your project.

Hope this helps.

**Comment by vraj129** [comment]
Thanks @Knightro63 this worked.
