### ISSUE TITLE
我想加入

### ISSUE THREAD

**Issue by xiaojieonly** [wasabia/three_dart#2]
我是FlutterCandies里的'复读机'，晚上在群里看到你发布的这个项目，个人非常感兴趣，想要加入这个项目，一起研究~~~😀😀😀

![image](https://user-images.githubusercontent.com/49278135/141511820-ffdb0c92-13ed-4285-a199-627d8a7c50b5.png)

**Comment by wasabia** [comment]
欢迎一起加入 PR
