### ISSUE TITLE
RangeError (index): Invalid value: Only valid value is 0: 1

### ISSUE THREAD

**Issue by lisen87** [wasabia/three_dart#25]
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: RangeError (index): Invalid value: Only valid value is 0: 1
    #0      List.[] (dart:core-patch/growable_array.dart:281:36)
    #1      OBJLoader.parse (package:three_dart_jsm/three_dart_jsm/loaders/OBJLoader.dart:522:38)
    #2      OBJLoader.load.<anonymous closure> (package:three_dart_jsm/three_dart_jsm/loaders/OBJLoader.dart:398:26)
    #3      OBJLoader.load.<anonymous closure> (package:three_dart_jsm/three_dart_jsm/loaders/OBJLoader.dart:395:22)
    #4      FileLoader.load (package:three_dart/three3d/loaders/FileLoader.dart:197:57)
    <asynchronous suspension>

模型 使用demo中 male02.obj ，手机系统 7.1.1

**Comment by wasabia** [comment]
使用github的最新代码试试
