### ISSUE TITLE
Run example on Android failure

### ISSUE THREAD

**Issue by nal-khangpt** [wasabia/three_dart#28]
I got error when try to run debug mode on Android emulator:

![Screen Shot 2022-03-29 at 1 32 19 PM](https://user-images.githubusercontent.com/93504043/160548600-9e85b08f-a2e3-470d-b44a-beb898c00035.png)

Flutter version:
![Screen Shot 2022-03-29 at 1 34 21 PM](https://user-images.githubusercontent.com/93504043/160548752-64f5f0ec-566f-4f1e-90d3-4110a6bfbbb4.png)

**Comment by victoreronmosele** [comment]
From the documentation of [flutter_gl](https://github.com/wasabia/flutter_gl#android-1)
> Android
> check the example project copy the example/android/app/libs/aars/threeegl.aar to your app android project same path
> 
> change minSdkVersion 24
