### ISSUE TITLE
大佬威武,请问下物理引擎现在又集成吗?或者有没有推荐,谢谢

### ISSUE THREAD

**Issue by ideryi** [wasabia/three_dart#4]
感觉图形的东西已经很牛逼了,就是dart的物理引擎没找到,不知道有没有计划集成,或者有没有建议呢?谢谢大佬!!!

**Comment by wasabia** [comment]
目前没有计划，可以考虑把javascript实现的物理引擎用dart重写一下 

[https://github.com/pmndrs/cannon-es](https://github.com/pmndrs/cannon-es)

**Comment by ideryi** [comment]
好的,谢谢大佬
