### ISSUE TITLE
Will be the best dart 3D library. Come on!

### ISSUE THREAD

**Issue by Flynn2018** [wasabia/three_dart#49]
3D library for dart re-written from Three.js is very needed. Hope it can be more powerful and have full functions.

Also, could you provided the license info?

**Comment by wasabia** [comment]
MIT License 😄   would be added later.

**Comment by ykmnkmi** [comment]
Any plans to use vector_math for vectors, matrixes and computations?

**Comment by wasabia** [comment]
> Any plans to use vector_math for vectors, matrixes and computations?

maybe no plan,
for matrixes we need use NativeArray from flutter_gl, so no need memory copy when send data to GPU。

**Comment by wasabia** [comment]
MIT License added
