### ISSUE TITLE
加载gltf模型

### ISSUE THREAD

**Issue by heyhuo** [wasabia/three_dart#5]
加载gltf模型时报错。
E/flutter (14676): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: Class 'GLTFMaterialsClearcoatExtension' has no instance getter 'createNodeMesh'.
E/flutter (14676): Receiver: Instance of 'GLTFMaterialsClearcoatExtension'
E/flutter (14676): Tried calling: createNodeMesh
E/flutter (14676): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68:5)
E/flutter (14676): #1      GLTFParser.loadNode.<anonymous closure> (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:1461:18)
E/flutter (14676): #2      GLTFParser._invokeOne (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:210:30)
E/flutter (14676): #3      GLTFParser.loadNode (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:1459:36)
E/flutter (14676): #4      GLTFParser.getDependency (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:256:35)
E/flutter (14676): #5      GLTFParser.buildNodeHierachy (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:1594:29)
E/flutter (14676): #6      GLTFParser.loadScene (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:1703:13)
E/flutter (14676): #7      GLTFParser.getDependency (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:252:35)
E/flutter (14676): #8      GLTFParser.getDependencies (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:345:31)
E/flutter (14676): #9      GLTFParser.parse (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFParser.dart:93:32)
E/flutter (14676): #10     GLTFLoader.parse (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFLoader.dart:332:12)
E/flutter (14676): #11     GLTFLoader.load.<anonymous closure> (package:three_dart_jsm/three_dart_jsm/loaders/gltf/GLTFLoader.dart:131:15)
E/flutter (14676): #12     FileLoader.load (package:three_dart/three3d/loaders/FileLoader.dart:136:59)

**Comment by heyhuo** [comment]
var loader = THREE_JSM.GLTFLoader(null)..setPath("assets/models/gltf/");
    loader.load("kindred_sketchfab.gltf", (gltf) {
      gltf.scene.position.y = 8;
      scene.add(gltf.scene);
      render();
    }, null, null);

**Comment by heyhuo** [comment]
可以在example里加一个加载gltf模型的例子吗？

**Comment by wasabia** [comment]
已经更新了 
添加了官方的example
https://threejs.org/examples/?q=gltf#webgl_loader_gltf

使用github版本  flutter_gl  three_dart_jsm 都需要 clone到本地 使用

**Comment by wasabia** [comment]
当前不支持 glb 格式

**Comment by wasabia** [comment]
暂时关闭了，有问题再打开
