### ISSUE TITLE
Can we create multiple child webgl context on parent widget  ?

### ISSUE THREAD

**Issue by MapleNoise** [wasabia/three_dart#51]
I have a trouble when I call 2 widgets which contains webgl context on my parent widget :

If I take your `webgl_animation_keyframes.dart` and `webgl_loader_gltf.dart` from your example :

```
Column(
    children: [
        webgl_loader_gltf(),
        webgl_animation_keyframes(),
    ]
)
```
I've this result (only the second load) :

![Screenshot_20220429-113236](https://user-images.githubusercontent.com/1905622/165920152-b29ba1d0-911e-4e2c-a559-9644b76d341e.jpg)

When I use 2 animated gltf differents, I have an animation conflict on the second child widgets and the first is black :
(Normaly the character should be in the top widget and c3po in the bottom widget)

![ezgif-3-9b8c4d146b](https://user-images.githubusercontent.com/1905622/165922113-acf89537-c442-45a2-8c4d-a973a6676307.gif)

I already check this kind of solution but it's hard to apply in flutter/dart context :
https://webglfundamentals.org/webgl/lessons/webgl-multiple-views.html

Do you have an explanation or solution ?

Thanks for your library 🙏

**Comment by wasabia** [comment]
Hi @MapleNoise 

now flutter_gl not support multi opengl contexts

but i think you wanted is use viewport to show multiple views

it is supported 

have a look threejs example [https://threejs.org/examples/?q=view#webgl_multiple_views](https://threejs.org/examples/?q=view#webgl_multiple_views)

or 

three_dart example

[https://wasabia.github.io/three_dart_example/#/examples/webgl_camera](https://wasabia.github.io/three_dart_example/#/examples/webgl_camera)

use viewport to show multiple

**Comment by MapleNoise** [comment]
It's ok for me, don't forget to add/update the `autoclear` params in the `render()` function :

Works fine with .gltf 

```
  render() {
    int _t = DateTime.now().millisecondsSinceEpoch;

    final _gl = three3dRender.gl;

    renderer!.setViewport(0, 0, 100, 100);
    renderer!.render(scene, camera);

    renderer!.autoClear = false;

    renderer!.setViewport(100, 0, 100, 100);
    renderer!.render(scene, camera2);

    renderer!.autoClear = false;

    renderer!.setViewport(200, 0, 100, 100);
    renderer!.render(scene, camera3);

    renderer!.autoClear = true;

    int _t1 = DateTime.now().millisecondsSinceEpoch;

    if (verbose) {
      print("render cost: ${_t1 - _t} ");
      print(renderer!.info.memory);
      print(renderer!.info.render);
    }
    
    _gl.flush();

    if (verbose) print(" render: sourceTexture: $sourceTexture ");

    if (!kIsWeb) {
      three3dRender.updateTexture(sourceTexture);
    }
  }
```
