### ISSUE TITLE
Add analysis_options.yml to the project and fix linting

### ISSUE THREAD

**Issue by mark-apn** [wasabia/three_dart#54]
First of all, really appreciate the hard work! Really cool to see that we can have truly 3d capabilities in Flutter!

If we want to have this package take off, I suggest to add some form of linting to clean up the code a bit. My suggestion would be to make a separate branch, and enable only 1 or 2 rules at first. After thats in place keep on adding more rules to improve the code quality. I would be more than happy to help out and get this going.

If you want I can start with adding an analysis file and adding return types and getting rid of dynamics where I can. Would that be something that would be appreciated?

**Comment by wasabia** [comment]
It's cool! feel free to start it.

**Comment by renancaraujo** [comment]
Hello @wasabia, Thanks for your hard work. I also saw myself having concerns regarding code quality and performance when doing [this](https://github.com/renancaraujo/three_experiment). 

With the lint rules that are already established, we get 1700 violations only in this repo, let alone flutter_gl. 

So before opening any pull requests, are you open to a large-scale contribution to improve the codebase quality?

**Comment by wasabia** [comment]
@renancaraujo 
Yes
Contributions of any kind welcome!

**Comment by mark-apn** [comment]
First batch of lint fixes are now merged via https://github.com/wasabia/three_dart/pull/95. 

More to come in the coming days/weeks. After that we can try to work towards elliminating all `dynamic` references and make the package more solid.

**Comment by mark-apn** [comment]
Second batch of lint fixes just landed. Ill create a new ticket for moving away from dynamic types
