### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by zhou67832033** [wasabia/three_dart#6]
Error Log:

Height of Platform View type: [1640681274879000] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [1640681274879000] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
 OpenGLContextWeb 
{gl: [object WebGL2RenderingContext]}
 WebGLState..................init........... 
 WebGLState. getParameter _data: [0, 0, 2400, 1504]
THREE.WebGLProgram: gl.getProgramInfoLog() programLog: WARNING: Output of vertex shader 'vUv' not read by fragment shader
 vertexLog:  fragmentLog:  
Error: Expected a value of type 'List<num>', but got one of type 'Float32Array'

**Comment by wasabia** [comment]
那个example？ 报错代码？ 运行环境 web 还是app

**Comment by zhou67832033** [comment]
example: webgl_camera_array
运行环境: web

======== Exception caught by gesture ===============================================================
The following TypeErrorImpl was thrown while handling a gesture:
Expected a value of type 'List<num>', but got one of type 'Float32Array'

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 84:3        castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 452:10  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/classes.dart 635:14     as_C
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 201:40  _argumentErrors
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 398:10  callMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 402:5   dsend
packages/three_dart/three3d/renderers/webgl/WebGLUniformsHelper.dart 633:10       setValueM4
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 398:10  callMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 402:5   dsend
packages/three_dart/three3d/renderers/webgl/WebGLUniforms.dart 84:55              setValue
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 398:10  callMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 402:5   dsend
packages/three_dart/three3d/renderers/WebGLRenderer.dart 1424:15                  setProgram
packages/three_dart/three3d/renderers/WebGLRenderer.dart 568:28                   renderBufferDirect
packages/three_dart/three3d/renderers/WebGLRenderer.dart 1120:10                  renderObject
packages/three_dart/three3d/renderers/WebGLRenderer.dart 1053:13                  renderObjects
packages/three_dart/three3d/renderers/WebGLRenderer.dart 819:78                   render
packages/example/webgl_camera_array.dart 170:5                                    render
packages/example/webgl_camera_array.dart 124:13                                   <fn>
packages/flutter/src/material/ink_well.dart 989:21                                [_handleTap]
packages/flutter/src/gestures/recognizer.dart 198:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 608:48                                     handleTapUp
packages/flutter/src/gestures/tap.dart 296:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 230:7                                      handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 563:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 94:12                           [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 139:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13          forEach
packages/flutter/src/gestures/pointer_router.dart 137:17                          [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 123:7                           route
packages/flutter/src/gestures/binding.dart 439:19                                 handleEvent
packages/flutter/src/gestures/binding.dart 419:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 322:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 374:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 338:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 296:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 279:32                                 [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1026:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 184:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 130:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 558:18                                    <fn>
lib/_engine/engine/pointer_binding.dart 511:21                                    <fn>
lib/_engine/engine/pointer_binding.dart 217:16                                    loggedHandler
Handler: "onTap"
Recognizer: TapGestureRecognizer#f0d04
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(1160.5, 711.5)
  finalLocalPosition: Offset(32.5, 31.5)
  button: 1
  sent tap down
====================================================================================================


[✓] Flutter (Channel beta, 2.9.0-0.1.pre, on macOS 11.2.2 20D80 darwin-arm, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
[✓] Connected device (1 available)

**Comment by zhou67832033** [comment]
example: webgl_camera_array
运行环境: web

======== Exception caught by gesture ===============================================================
The following TypeErrorImpl was thrown while handling a gesture:
Expected a value of type 'List<num>', but got one of type 'Float32Array'

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 84:3        castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 452:10  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/classes.dart 635:14     as_C
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 201:40  _argumentErrors
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 398:10  callMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 402:5   dsend
packages/three_dart/three3d/renderers/webgl/WebGLUniformsHelper.dart 633:10       setValueM4
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 398:10  callMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 402:5   dsend
packages/three_dart/three3d/renderers/webgl/WebGLUniforms.dart 84:55              setValue
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 398:10  callMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 402:5   dsend
packages/three_dart/three3d/renderers/WebGLRenderer.dart 1424:15                  setProgram
packages/three_dart/three3d/renderers/WebGLRenderer.dart 568:28                   renderBufferDirect
packages/three_dart/three3d/renderers/WebGLRenderer.dart 1120:10                  renderObject
packages/three_dart/three3d/renderers/WebGLRenderer.dart 1053:13                  renderObjects
packages/three_dart/three3d/renderers/WebGLRenderer.dart 819:78                   render
packages/example/webgl_camera_array.dart 170:5                                    render
packages/example/webgl_camera_array.dart 124:13                                   <fn>
packages/flutter/src/material/ink_well.dart 989:21                                [_handleTap]
packages/flutter/src/gestures/recognizer.dart 198:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 608:48                                     handleTapUp
packages/flutter/src/gestures/tap.dart 296:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 230:7                                      handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 563:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 94:12                           [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 139:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13          forEach
packages/flutter/src/gestures/pointer_router.dart 137:17                          [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 123:7                           route
packages/flutter/src/gestures/binding.dart 439:19                                 handleEvent
packages/flutter/src/gestures/binding.dart 419:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 322:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 374:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 338:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 296:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 279:32                                 [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1026:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 184:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 130:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 558:18                                    <fn>
lib/_engine/engine/pointer_binding.dart 511:21                                    <fn>
lib/_engine/engine/pointer_binding.dart 217:16                                    loggedHandler
Handler: "onTap"
Recognizer: TapGestureRecognizer#f0d04
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(1160.5, 711.5)
  finalLocalPosition: Offset(32.5, 31.5)
  button: 1
  sent tap down
====================================================================================================


[✓] Flutter (Channel beta, 2.9.0-0.1.pre, on macOS 11.2.2 20D80 darwin-arm, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
[✓] Connected device (1 available)

**Comment by zhou67832033** [comment]
编译时：
three3dRender = FlutterGlPlugin(); 报错
我改成了：
three3dRender = FlutterGlPlugin(width.toInt(), height.toInt());

另外在 webgl_loader_gltf 例子中
var _loader = THREE_JSM.RGBELoader(null);
提示：The function 'RGBELoader' isn't defined

**Comment by wasabia** [comment]
把相关的插件 都clone到本地使用本地版本不要使用 pub.dev 版本  基本都没有更新呢

**Comment by wasabia** [comment]
flutter_gl 
three_dart 
three_dart_jsm 
看看example/pubspec.yaml里的设置

**Comment by wasabia** [comment]
我这边测试的没有问题

**Comment by zhou67832033** [comment]
好的，我克隆到本地试试

**Comment by zhou67832033** [comment]
希望能更新下 pub.dev

**Comment by wasabia** [comment]
好的 暂时使用github 也可以 自己fork一下

**Comment by zhou67832033** [comment]
在本地跑起来了，效果很棒！

**Comment by wasabia** [comment]
有问题 欢迎提issue PR
