### ISSUE TITLE
请教如何把TextGeometry  转化为 Sprite

### ISSUE THREAD

**Issue by coreuml** [wasabia/three_dart#65]
请教如何把TextGeometry  转化为 Sprite

需要Render到一个临时Texture，然后转换吗？里面有个CanvasTexture，这个构造函数需要一个Canvas参数，这个参数是几何体吗？可以出个示例吗？

**Comment by wasabia** [comment]
直接把TextGeometry渲染到RenderTarget 然后 RenderTarget的texture可以传给Sprite

**Comment by coreuml** [comment]
> 

谢谢，非常感谢。
