### ISSUE TITLE
示例代码，在Widnows 10下运行，无法显示三维元素

### ISSUE THREAD

**Issue by coreuml** [wasabia/three_dart#67]
示例代码，在Widnows 10下运行，无法显示三维元素，窗口背景色设置成功，输出有日志提示：
Error compiling shader: vertexLog: null fragmentLog: null

是我的配置问题？

**Comment by wasabia** [comment]
windows 下 openGL shader glsl 兼容性问题吧
现在没有windows设备调试
可以自己调试看看

**Comment by coreuml** [comment]
> 

好的
