### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by Coimbra1984** [wasabia/three_dart#8]
Hi,
you mention that you would need flutter_gl to work on desktops in order to have desktop support.
Can't you just use regular openGL (without ES) directly on desktop systems:
https://pub.dev/packages/opengl

Just to give you an idea...

**Comment by wasabia** [comment]
seems it is just a dart library, run with no flutter on desktop.

i had push flutter_gl_macos to github repo 

but still have problem 

[https://github.com/wasabia/flutter_gl/issues/6](https://github.com/wasabia/flutter_gl/issues/6)

**Comment by wasabia** [comment]
macos support now

**Comment by Coimbra1984** [comment]
Nice, but I would need windows support.

**Comment by wasabia** [comment]
flutter_gl support windows now.
