### ISSUE TITLE
Flutter_gl issue when running on flutter 3.3.1

### ISSUE THREAD

**Issue by SerJoG** [wasabia/three_dart#80]
I'm trying to run flutter app with three_dart, I have this failure;
![image](https://user-images.githubusercontent.com/23215134/190693936-b01cd583-130d-4e9a-9a81-6a50942b8b75.png)
and then this exception (I post it too for the sake of completeness).
![image](https://user-images.githubusercontent.com/23215134/190695090-e3541f64-da92-41d9-89ee-7cfb09d87a92.png)

**Comment by wasabia** [comment]
follow flutter_gl android setup
[https://github.com/wasabia/flutter_gl#android](https://github.com/wasabia/flutter_gl#android)

**Comment by wasabia** [comment]
[https://github.com/wasabia/flutter_gl#android-1](https://github.com/wasabia/flutter_gl#android-1)

**Comment by SerJoG** [comment]
I haven't the lib/aars under android/app. How i can fix it?

**Comment by wasabia** [comment]
copy the example/android/app/libs/aars/threeegl.aar to your app android project same path
