### ISSUE TITLE
Controls in Android or ios

### ISSUE THREAD

**Issue by SerJoG** [wasabia/three_dart#84]
Sorry for bothering you. How can I enable controls like rotation and zoom in mobile device like arcbal or trackball? I tried to see these but threejsm.Trackballcontrols and threejsm.arcballcontrols raise an exception that tells that null check on a null value, but I copied your example.

**Comment by wasabia** [comment]
[https://github.com/wasabia/three_dart/blob/main/example/lib/misc_controls_trackball.dart](https://github.com/wasabia/three_dart/blob/main/example/lib/misc_controls_trackball.dart)

Works as expected on iOS, i did not see any error.

**Comment by mark-apn** [comment]
Closing issue as it is answered and there was no followup. Please add a new issue if you have any more questions
