### ISSUE TITLE
Asset to Mesh

### ISSUE THREAD

**Issue by SerJoG** [wasabia/three_dart#85]
Is it possible to convert an asset like a glb or obj file into meshes? Like the import of blender.

**Comment by wasabia** [comment]
[https://github.com/wasabia/three_dart/blob/main/example/lib/webgl_loader_obj.dart](https://github.com/wasabia/three_dart/blob/main/example/lib/webgl_loader_obj.dart)

use Obj Loader or gltf Loader, only support gltf, not support glb

**Comment by SerJoG** [comment]
but then can i select portions of renderer object?

**Comment by mark-apn** [comment]
Obj import of a blender file is working. You can search thru the object children to find specific parts of the object. Hope this answers your question. Feel free to open a new issue if you have any problems.
