### ISSUE TITLE
加载复杂纹理的GLTF模型

### ISSUE THREAD

**Issue by heyhuo** [wasabia/three_dart#86]
GLTF模型有复杂纹理的时候，在three.js上可以流畅加载，在three_dart上直接卡死
有考虑优化下加载的性能吗？

模型链接：https://wwz.lanzouv.com/irGOv0cc30fi

**Comment by wasabia** [comment]
什么环境下？
移动端？还是web？

**Comment by heyhuo** [comment]
> 什么环境下？ 移动端？还是web？

移动端，安卓机，测试机型：红米K50，内存8G，苹果机：iphoneXR

**Comment by wasabia** [comment]
在桌面端 PC WEB 都正常
![image](https://user-images.githubusercontent.com/1768228/192147317-d3b68f0b-8f49-48f2-a96b-73d9e443d8a9.png)

**Comment by heyhuo** [comment]
> 

可以试下在移动端加载，帧率应该是在10以下

**Comment by wasabia** [comment]
现在加载都是在main isolate 里，应该是加载中 会影响UI渲染吧 加载完 后应该没问题，
这个 估计要自己优化一下 把加载放到isolate里？

**Comment by wasabia** [comment]
现在加载都是在main isolate 里，应该是加载中 会影响UI渲染吧 加载完 后应该没问题，
这个 估计要自己优化一下 把加载放到isolate里？

**Comment by heyhuo** [comment]
> 现在加载都是在main isolate 里，应该是加载中 会影响UI渲染吧 加载完 后应该没问题， 这个 估计要自己优化一下 把加载放到isolate里？

加载完之后，用orbitControll滑动界面的帧率很低，没办法像在three.js一样流畅的切换视角，这个有什么优化的解决办法嘛？

**Comment by wasabia** [comment]
简单看了一下 好像透明的材质比较多 耗时久一点 有时间再看一下 为什么慢

**Comment by wasabia** [comment]
[https://github.com/wasabia/three_dart/blob/main/lib/three3d/renderers/WebGLRenderer.dart#L1015](https://github.com/wasabia/three_dart/blob/main/lib/three3d/renderers/WebGLRenderer.dart#L1015)

应该是这里的问题了 getParameters和getProgramCacheKey 耗时占比高一些 大量透明材质时需要getProgram

**Comment by heyhuo** [comment]
> https://github.com/wasabia/three_dart/blob/main/lib/three3d/renderers/WebGLRenderer.dart#L1015
> 
> 应该是这里的问题了 getParameters和getProgramCacheKey 耗时占比高一些 大量透明材质时需要getProgram

我现在在做一个模型和动作匹配展示的功能
b站链接：【Flutter加载VRM模型和FBX动作-哔哩哔哩】 https://b23.tv/6KoD88D

但是在flutter上性能不太好，画面有撕裂的情况，不知道是不是也跟webglrender的渲染性能有关系

**Comment by wasabia** [comment]
非常赞！
现在是有不少BUG，性能应该也有不少优化的空间。
当前只是单纯的代码从js转到dart。

**Comment by wasabia** [comment]
我发现在macOS debug性能居然比release 更好。 😒

**Comment by mark-apn** [comment]
Can this issue be closed? Of does it still need a solution :-) If its pure a performance issue, maybe we should create a separate issue that covers the performance concerns
