### ISSUE TITLE
Missing package references when building project containing three_dart

### ISSUE THREAD

**Issue by mark-apn** [wasabia/three_dart#94]
I'm seeing wierd missing class/function errors in my pipeline and in the action logs in this repo. 

Worth investigating what the cause of this might be. 

I have created an issue at the `dart pub` repo to see if they can help pinpoint the cause of this problem. (
https://github.com/dart-lang/pub/issues/3601)

This is also the likely cause of all failing actions on this repo: https://github.com/wasabia/three_dart/actions

**Comment by mark-apn** [comment]
@wasabia Still getting them on the latest commit sadly. Any other ideas?

![image](https://user-images.githubusercontent.com/62654433/196110450-4fee11da-d0d2-4c7e-849f-99802bdf9a45.png)

**Comment by wasabia** [comment]
currently i have no idea!
build web in release mode is ok on my macbook.
but can not work on Github  Actions.

**Comment by mark-apn** [comment]
Fixed by changing the last files to lowercase in this PR https://github.com/wasabia/three_dart/pull/102

Probably linux in CI being more strict with case sensitivity
