### ISSUE TITLE
react-three-fiber like declarative API?

### ISSUE THREAD

**Issue by satvikpendem** [wasabia/three_dart#99]
Any thoughts on a [react-three-fiber](https://github.com/pmndrs/react-three-fiber) like declarative API for three_dart? Basically r3f turns the imperative API into something based around components (aka widgets in the Flutter world). Since Flutter borrows a lot from React, like its component based style, it would be something to look into, I believe.

Three.js: https://codesandbox.io/s/reurope-threejs-basic-kiow9?file=/src/index.js
R3F: https://codesandbox.io/s/reurope-r3f-basic-7kuzy?file=/src/App.js

**Comment by mark-apn** [comment]
Look really cool, but for now out of scope for this library. We're working on improving the base we have now and fixing the code quality and after that preparing for null safety and Flutter 3. Maybe this could be done in a separate repo on top of this! 

I would certainly applaud any effort that is done to build such a package!
